const OrderStatus = Object.freeze({
    INITIATED: 'INITIATED',
    PENDING: 'PENDING',
    CAPTURE: 'CAPTURE',
    SETTLEMENT: 'SETTLEMENT',
    DENY: 'DENY',
    CANCEL: 'CANCEL',
    EXPIRE: 'EXPIRE',
    FAILURE: 'FAILURE',
    REFUND: 'REFUND',
    CHARGEBACK: 'CHARGEBACK',
    PARTIAL_REFUND: 'PARTIAL_REFUND',
    PARTIAL_CHARGEBACK: 'PARTIAL_CHARGEBACK',
    AUTHORIZE: 'AUTHORIZE',
    ON_DELIVERY: 'ON_DELIVERY',
    FINISHED: 'FINISHED',
});

const CustomerOrderStatus = Object.freeze({
    PENDING_PAYMENT: 'PENDING PAYMENT',
    PAID: 'PAID',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED',
    EXPIRED: 'EXPIRED',
    REFUNDED: 'REFUNDED',
    PARTIALLY_REFUNDED: 'PARTIALLY REFUNDED',
    ON_DELIVERY: 'ON DELIVERY',
    COMPLETED: 'COMPLETED',
})

export { OrderStatus, CustomerOrderStatus }